{% set name = "pyvitae" %}
{% set version = "2.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b7c51c40142f008f5081c5cd3080b2fa8472ee697c98005466c8054b805bd57e

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - jupyter
    - leidenalg
    - matplotlib-base
    - networkx
    - numpy ==1.23
    - numba
    - pandas
    - python >=3.8
    - scanpy >=1.8.2
    - scikit-learn
    - seaborn
    - statsmodels
    - tensorflow >=2.4
    - tensorflow-probability >=0.13
    - umap-learn >=0.5.0


test:
  imports:
    - VITAE

about:
  home: https://github.com/jaydu1/VITAE
  summary: 'Joint Trajectory Inference for Single-cell Genomics Using Deep Learning with a Mixture Prior'
  description: |
    Joint Trajectory Inference for Single-cell Genomics Using Deep Learning with a Mixture Prior
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://jaydu1.github.io/VITAE/
  dev_url: https://github.com/jaydu1/VITAE

extra:
  recipe-maintainers:
    - jaydu1
