{% set name = "pyvitae" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 07a277fc9a4051f453656ee625581ce795ac85ce3b102879b7cccdb8d5b029f0


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jupyter
    - leidenalg
    - matplotlib-base
    - networkx
    - numpy ==1.23
    - numba
    - pandas
    - python >={{ python_min }}
    - scanpy >=1.8.2
    - scikit-learn
    - seaborn
    - statsmodels
    - tensorflow >=2.4,<2.16
    - tensorflow-probability >=0.13
    - umap-learn >=0.5.0


test:
  requires:
    - python {{ python_min }}
  imports:
    - VITAE

about:
  home: https://github.com/jaydu1/VITAE
  summary: 'Joint Trajectory Inference for Single-cell Genomics Using Deep Learning with a Mixture Prior'
  description: |
    Joint Trajectory Inference for Single-cell Genomics Using Deep Learning with a Mixture Prior
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://jaydu1.github.io/VITAE/
  dev_url: https://github.com/jaydu1/VITAE

extra:
  recipe-maintainers:
    - jaydu1
